on:
  release:
    types:
      - published

jobs:
  pypi-publish:
    name: Upload release to PyPi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/framebench
    permissions:
      id-token: write
    steps:
      - name: Fetch code
        uses: actions/checkout@v3
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Build sdist
        run: python3 setup.py sdist
      
      - name: Upload to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1  